### ISSUE TITLE
Pagina web

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-gregorio-8us#1]
[practica2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-equipo-gregorio-8us/files/14923383/practica2.pdf)

**Comment by salathiel1999** [comment]
18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
